[package]
name = "pai-unicode"
description = "Pai Unicode"
version.workspace = true
edition.workspace = true

[dependencies]


[build-dependencies]
pai-error.workspace = true
pai-file.workspace = true
