[package]
name = "pai-unicode"
description = "Pai Unicode"
version.workspace = true
edition.workspace = true

[lib]

[features]
default = []


[dependencies]


[build-dependencies]
pai-error.workspace = true
pai-file.workspace = true
