[registries.crates-io]
protocol = "sparse"

[env]
# rebuild AutoGen if release
ENV_AUTOGEN_PROFILE = ""

ENV_PAI_UNICODE_AUTOGEN_DIR = { value = "crates/pai-unicode/__AutoGen__", relative = true }
ENV_PAI_UNICODE_DOWNLOAD_DIR = { value = "crates/pai-unicode/__download__", relative = true }

[alias]
build-release = "build --release --timings=html"

[build]
rustflags = ["-Z", "threads=8"]

[unstable]
unstable-options = true
