[package]
name = "pai-lexer"
description = "Pai Lexer"
version.workspace = true
edition.workspace = true

[lib]

[features]

[dependencies]
pai-file.workspace = true
pai-error.workspace = true
pai-unicode.workspace = true

[dev-dependencies]
insta.workspace = true
